### ISSUE TITLE
could not resolve dependencies

### ISSUE THREAD

**Issue by liwoxa** [lsmor/snake-fury#4]
When trying to install with cabal, dependencies resolution fails:

```
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: snake-fury-0.1.0.0 (user goal)
[__1] next goal: base (dependency of snake-fury)
[__1] rejecting: base-4.16.3.0/installed-4.16.3.0 (conflict: snake-fury =>
base^>=4.14)
[__1] skipping: base-4.17.0.0, base-4.16.4.0, base-4.16.3.0, base-4.16.2.0,
base-4.16.1.0, base-4.16.0.0, base-4.15.1.0, base-4.15.0.0 (has the same
characteristics that caused the previous version to fail: excluded by
constraint '^>=4.14' from 'snake-fury')
[__1] rejecting: base-4.14.3.0, base-4.14.2.0, base-4.14.1.0, base-4.14.0.0,
base-4.13.0.0, base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__1] fail (backjumping, conflict set: base, snake-fury)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, snake-fury
```

Fixed by removing all of the `^` symbols from the `snake-fury.cabal` file and updating the resolver url in `stack.yaml` to:

```
https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/7.yaml
```

With this I got the VSCode extension to work too.

**Comment by lsmor** [comment]
HI, thanks for the report and sorry for the problems. 

This is likely due to different `ghc` version. This was originally build with `ghc-8.10.7`. Since it uses very stable libraries there shouldn't be a problem building with a different ghc version. I just need to relax the constraints

Are you using `stack` or `cabal`?

**Comment by liwoxa** [comment]
I guess `cabal`. This was a while ago so I don't remember exactly, but somehow I needed both of these to get the VSCode extension to work. The main point of the issue was the deal with the `cabal` packages.

(No need to apologies, I'm very grateful for the work you put into this repo :)

**Comment by lsmor** [comment]
> I guess `cabal`.

Well if you build with `cabal build` then you are using `cabal`. If you build with `stack build` then you use `stack`. In general, `cabal` is enough to get VScode extension to work, but I have suffered `hls` issues with that kind of things too. :disappointed: 

That's being said, I am closing this issue with [this commit](https://github.com/lsmor/snake-fury/commit/357a27a3bc77336eabb0f64044b68df8d660f7ef). Essentially I have relax dependency bound. Because I am using very common dependencies, there should be no failure in the building plan. 

Later I'll create different `stack` file for each compiler version. 

Thanks for informing about the dependencies. Btw, if you feel ok with it, open an issue once you finish the project with some feedback :). I'd appreciate that
